### ISSUE TITLE
Get node:events:504 error when using tools to run the pre-upgrade health check

### ISSUE THREAD

**Issue by yuehd** [ibm-apiconnect/apicops#10]
We downloaded the [apicops-v10 0.10.56](https://github.com/ibm-apiconnect/apicops/releases/tag/v0.10.56) tool in redhat server. And login the apic mgmt and then run the pre-upgrade health check, it always show the error message as blow. Would you kindly help to verify it. thank you.

apic version: v10.0.1.7

1.  ./apic-slim login -s  apic-mgmt-platform-api-apic.preprod-workload-cluster-41aabf0d7901b34f1c6c5a84c6111ae8-i002.eu-gb.containers.appdomain.cloud --realm admin/default-idp-1 -u admin -p '**********'
Warning: Using default toolkit credentials.
Logged into apic-mgmt-platform-api-apic.preprod-workload-cluster-41aabf0d7901b34f1c6c5a84c6111ae8-i002.eu-gb.containers.appdomain.cloud successfully
2. export KUBECONFIG=/root/.kube/config
3. ./apicops-v10  version:pre-upgrade -n apic
Current local date/time 8/4/2022, 9:23:07 AM [Current UTC time: 2022-08-04T09:23:07.176Z]
apicops-v10 0.10.56 (Postgres)
Pod version is: 10.0.1.7-4979-eus ( ibm-apiconnect-management-apim@sha256:24b7e97019e877be197996640efdc875f4953f9d8171adf3a07f411ee52246cb )

? Please confirm that apicops commands that run on a cron have been disabled for the duration of this script: yes
 Start: apicops-v10 version:pre-upgrade 
Getting Topology info
Command: apicops-v10 topology
? Please enter the Cloud Manager 'admin' password: 
node:events:504
      throw er; // Unhandled 'error' event
      ^
Error: write EPIPE
    at afterWriteDispatched (node:internal/stream_base_commons:160:15)
    at writeGeneric (node:internal/stream_base_commons:151:3)
    at Socket._writeGeneric (node:net:795:11)
    at Socket._write (node:net:807:8)
    at writeOrBuffer (node:internal/streams/writable:389:12)
    at _write (node:internal/streams/writable:330:10)
    at Socket.Writable.write (node:internal/streams/writable:334:10)
    at Topology._doSpawn (/snapshot/jenkins/go/src/github.ibm.com/velox/apicops/src/lib/spawn/spawn.js:76:25)
    at new Promise (<anonymous>)
    at Topology.spawn (/snapshot/jenkins/go/src/github.ibm.com/velox/apicops/src/lib/spawn/spawn.js:97:22)
Emitted 'error' event on Socket instance at:
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -32,
  code: 'EPIPE',
  syscall: 'write'
}

**Comment by iainsoed** [comment]
For some reason apicops is not able to call the platform REST api, as defined here: https://www.ibm.com/docs/en/api-connect/10.0.5.x_lts?topic=settings-viewing-platform-ui-endpoints.

The part of the pre-upgrade check that requires this however is not essential and can be skipped by adding `--no-topology` to the call.
