### ISSUE TITLE
Still not working on Windows

### ISSUE THREAD

**Issue by danielcastellano** [ibm-apiconnect/apicops#3]
When trying to execute on Windows (apicops/0.2.51 win32-x64 node-v10.4.1) I get:

> Failed to spawn the command sh -c kubectl exec -it r9e8418c322-apim-v2-76764f58c7-j552v -- node -
> Error: write EPIPE
>     at afterWriteDispatched (internal/stream_base_commons.js:75:25)
>     at writeGeneric (internal/stream_base_commons.js:70:3)
>     at Socket._writeGeneric (net.js:757:5)
>     at Socket._write (net.js:769:8)
>     at doWrite (_stream_writable.js:410:12)
>     at writeOrBuffer (_stream_writable.js:394:5)
>     at Socket.Writable.write (_stream_writable.js:294:11)
>     at CleanupLocks._doSpawn (C:\snapshot\jenkins\go\src\github.ibm.com\velox\apicops\src\lib\spawn\spawn.js:71:25)
>     at new Promise (<anonymous>)
>     at CleanupLocks.spawn (C:\snapshot\jenkins\go\src\github.ibm.com\velox\apicops\src\lib\spawn\spawn.js:92:22)
> Failed to run the cleanupLocks.js script: Error: write EPIPE
> Error: write EPIPE
>     at afterWriteDispatched (internal/stream_base_commons.js:75:25)
>     at writeGeneric (internal/stream_base_commons.js:70:3)
>     at Socket._writeGeneric (net.js:757:5)
>     at Socket._write (net.js:769:8)
>     at doWrite (_stream_writable.js:410:12)
>     at writeOrBuffer (_stream_writable.js:394:5)
>     at Socket.Writable.write (_stream_writable.js:294:11)
>     at CleanupLocks._doSpawn (C:\snapshot\jenkins\go\src\github.ibm.com\velox\apicops\src\lib\spawn\spawn.js:71:25)
>     at new Promise (<anonymous>)
>     at CleanupLocks.spawn (C:\snapshot\jenkins\go\src\github.ibm.com\velox\apicops\src\lib\spawn\spawn.js:92:22)

It seems that it tries to execute a sh inside windows...

**Comment by danielcastellano** [comment]
Still the same on v0.2.86.

```
C:\Users\DanielCastellanoBoni\Desktop\Pasar\Clientes\Eurobits\eurobits>apicops locks:delete-expired
Current date/time 2020-03-13T08:48:45.797Z
apicops 0.2.68
Failed to spawn the command sh -c kubectl  exec -i r9e8418c322-apim-v2-76764f58c7-j552v -- node -
Error: write EPIPE
    at afterWriteDispatched (internal/stream_base_commons.js:75:25)
    at writeGeneric (internal/stream_base_commons.js:70:3)
    at Socket._writeGeneric (net.js:757:5)
    at Socket._write (net.js:769:8)
    at doWrite (_stream_writable.js:410:12)
    at writeOrBuffer (_stream_writable.js:394:5)
    at Socket.Writable.write (_stream_writable.js:294:11)
    at CleanupLocks._doSpawn (C:\snapshot\jenkins\go\src\github.ibm.com\velox\apicops\src\lib\spawn\spawn.js:71:25)
    at new Promise (<anonymous>)
    at CleanupLocks.spawn (C:\snapshot\jenkins\go\src\github.ibm.com\velox\apicops\src\lib\spawn\spawn.js:92:22)
Failed to run the cleanupLocks.js script: Error: write EPIPE
Error: write EPIPE
    at afterWriteDispatched (internal/stream_base_commons.js:75:25)
    at writeGeneric (internal/stream_base_commons.js:70:3)
    at Socket._writeGeneric (net.js:757:5)
    at Socket._write (net.js:769:8)
    at doWrite (_stream_writable.js:410:12)
    at writeOrBuffer (_stream_writable.js:394:5)
    at Socket.Writable.write (_stream_writable.js:294:11)
    at CleanupLocks._doSpawn (C:\snapshot\jenkins\go\src\github.ibm.com\velox\apicops\src\lib\spawn\spawn.js:71:25)
    at new Promise (<anonymous>)
    at CleanupLocks.spawn (C:\snapshot\jenkins\go\src\github.ibm.com\velox\apicops\src\lib\spawn\spawn.js:92:22)
```

**Comment by chrisdudley** [comment]
At this point let me extol the virtues of OSX and Linux. ;-)

In seriousness I would strongly recommend using one of those platforms - realistically windows is the least used operating system nowadays for development and server admin and so will most likely have niche bugs not seen elsewhere.

I don't have an ETA on a fix.

**Comment by danielcastellano** [comment]
If there is no ETA to support Windows, then a Windows version shouldn't be published. I'm using a IBM laptop and it's a Windows, so even if it's the least used OS, it's a corporation choice, and it is supported (or at least many IBM pages says that it is...)

**Comment by chrisdudley** [comment]
What IBM does and doesn't support for its employees to use really has no bearing on apicops. 
I'll remind you that you're posting on a github.com site - this is public. This is NOT IBM internal.

apicops is specifically a tool for use with L2/L3 assistance and because of how it works I am not at all surprised it has issues on windows, lots of kubectl based tools do.
It is not a core APIC component.

You're right that the windows version likely needs removing. In the meantime I suggest you use a linux or osx VM.
